### PR TITLE
Add HackNITR 3.0 Coming Soon Status

### PR DESCRIPTION
**Pull request by CIPHERTron**

### CODE REVIEW

**Review by abhibhaw — CHANGES_REQUESTED** [review]
Needs refactoring

**Review by riteshsp2000 — APPROVED** [review]

**Comment by riteshsp2000** [comment]
Check the preview script

Either remove the script completely or fix it with preview deploys to vercel

**Comment by nayakastha** [comment]
Why is the preview constantly failing?

**Comment by CIPHERTron** [comment]
> Check the preview script
> 
> Either remove the script completely or fix it with preview deploys to vercel

Cool. I guess we have to remove the firebase deploy script completely cuz it's on Vercel now

**Review by abhibhaw — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
