### PR TITLE
Setup PWA

### LINKED ISSUE #65: Make a PWA
To have better support for mobile views and have native integrations. 
Linked Issue #30

### PR DESCRIPTION
**Pull request by KoushikSahu**
Issue: #65
Passing all tests on lighthouse for PWA

### CODE REVIEW

**Comment by KoushikSahu** [comment]
The test failing seems to be login issue to firebase. What should I do to fix this?

**Comment by DesignrKnight** [comment]
@riteshsp2000 check review and merge please

**Comment by riteshsp2000** [comment]
Okay I checked it. It's a basic PWA and works. There isn't any service worker registration and stuff right? Also I don't think we need that so its cool I suppose.

**Review by riteshsp2000 — APPROVED** [review]

**Comment by riteshsp2000** [comment]
> The test failing seems to be login issue to firebase. What should I do to fix this?

Its cool. You don't have firebase-tools installed which is why this is failing. And even if you have, you might not have the access to project-kiwi

**Comment by KoushikSahu** [comment]
> Okay I checked it. It's a basic PWA and works. There isn't any service worker registration and stuff right? Also I don't think we need that so its cool I suppose.

It is actually using service workers. You can check it in the networking tab I think. There is an issue with lighthouse. Check this [issue regarding this problem](https://github.com/shadowwalker/next-pwa/issues/107)

**Comment by KoushikSahu** [comment]
> > The test failing seems to be login issue to firebase. What should I do to fix this?
> 
> Its cool. You don't have firebase-tools installed which is why this is failing. And even if you have, you might not have the access to project-kiwi
> 

No I actually don't have firebase-tools and neither do I have the access to project-kiwi. I just handled this issue purely as a web app enhancement without going into the Firebase aspect(which I don't know much of).

**Comment by riteshsp2000** [comment]
> > Okay I checked it. It's a basic PWA and works. There isn't any service worker registration and stuff right? Also, I don't think we need that so its cool I suppose.
> 
> It is actually using service workers. You can check it in the networking tab I think. There is an issue with a lighthouse. Check this [issue regarding this problem](https://github.com/shadowwalker/next-pwa/issues/107)

Does next-PWA handle it completely? coz as far as I remember we need to have a service worker file where we configure our apps as per our need. And there are quite a few configurations with that which I am not entirely aware of

**Comment by KoushikSahu** [comment]
> > > Okay I checked it. It's a basic PWA and works. There isn't any service worker registration and stuff right? Also, I don't think we need that so its cool I suppose.
> > 
> > It is actually using service workers. You can check it in the networking tab I think. There is an issue with a lighthouse. Check this [issue regarding this problem](https://github.com/shadowwalker/next-pwa/issues/107)
> 
> Does next-PWA handle it completely? coz as far as I remember we need to have a service worker file where we configure our apps as per our need. And there are quite a few configurations with that which I am not entirely aware of 

Yeah next-pwa makes the sw.js and worker file when the project is built. If you have built the project in your system then you can find them.

**Pull request merged**
