### PR TITLE
Remove Defer && Add HackNITR Calendar

### PR DESCRIPTION
**Pull request by CIPHERTron**

### CODE REVIEW

**Comment by abhibhaw** [comment]
@CIPHERTron Why so many commits?

**Comment by abhibhaw** [comment]
Duplicate commits?

**Comment by CIPHERTron** [comment]
> Duplicate commits?

Yes :(

**Comment by CIPHERTron** [comment]
> @CIPHERTron Why so many commits?

Squash Please @abhibhaw

**Comment by abhibhaw** [comment]
Check this: https://project-kiwi-1649edj1q-hacknitr2021.vercel.app/

**Comment by CIPHERTron** [comment]
> Check this: https://project-kiwi-1649edj1q-hacknitr2021.vercel.app/

Checked 👍

**Comment by abhibhaw** [comment]
And where is your latest commit? That defer one

**Comment by CIPHERTron** [comment]
> And where is your latest commit? That defer one

It's there
See 8th March

**Pull request merged**
